### ISSUE TITLE
objectPath: string Array not working for object paths

### ISSUE THREAD

**Issue by TBioucas** [ExodusMovement/redux-watch#17]
Hello. I am trying to use as an objectPath an array of strings with objects paths.

According to the [docs](https://github.com/ExodusMovement/redux-watch#usage) that should be possible. But when trying it i got the following results:

> This makes an trigger on the watch:

`watch(store.getState, ['myReducer']);`

> but something like this does not trigger:

`watch(store.getState, ['myReducer.myProp']);`

> if i change it to a single string, it triggers correctl:

`watch(store.getState, 'myReducer.myProp');`

So is it possible to make the watch trigger when having something like:

`watch(store.getState, ['myReducer.myProp','myReducer.myAnotherProp']);`

Thanks for the support.

**Comment by sahilshahane** [comment]
Same here, Please Fix this

**Comment by VityaSchel** [comment]
no fix bruh

**Comment by VityaSchel** [comment]
my solution:

```javascript
import _ from 'lodash'

export function watch(updateFunction, subscribedProperties) {
  let previousState = updateFunction()
  return listener => () => {
    const newState = updateFunction()
    if(!_.isEqual(previousState, newState)) {
      previousState = updateFunction()
      listener(_.pick(newState, subscribedProperties))
    }
  }
}
```

```javascript
import { watch } from './utils.js'
const w = watch(store.getState, ['property1', 'property2'])
store.subscribe(w(newState => console.log('new state!', newState)))
```

it cuts all other properties and only calls listener (newState => console.log('new state!', newState)) when values of properties ['property1', 'property2'] changes

**Comment by RyanZim** [comment]
The array form of path is not for passing multiple properties to watch, it's for passing segments of an object path individually. So for example, passing `['a', 'b']` is equivalent to passing `'a.b'`. `['myReducer.myProp']` doesn't work as you expect, because it's not looking for `myProp` in `myReducer`, it's looking for an actual property named `myReducer.myProp` in the state.
