### ISSUE TITLE
How to make order of calls to store.subscribe?

### ISSUE THREAD

**Issue by cleverocheck** [ExodusMovement/redux-watch#18]
I have a goal that one store.subscribe created by me is called later than the rest, regardless of the order in which it was added, how can this be done?

**Comment by RyanZim** [comment]
I'm not sure I understand. Are you trying to have one `store.subscribe` subscription be triggered later than all other subscriptions? If so, this is a question about Redux in general, not specific to redux-watch, and is therefore off-topic here.

**Comment by cleverocheck** [comment]
@RyanZim it's been 5 months I have long forgotten why I needed it. But I believe you correct understand me.

Maybe really this issue should be created in [redux core](https://github.com/reduxjs/redux), because [redux-watch](https://github.com/ExodusMovement/redux-watch) is just utils to work with `store.subscribe`. But I think features like it never won't be merged into the core because this breaks the essence of redux about subscriptions order.

Anyway we can just realize it in the our final project code via `store.subscribe` add-on: if `afterAll` flag is true, so call final callback last, but direct `store.subsribe` callback will be called as it should in the correct order (as I remember I did it). But it looks a little strange in final project code and can be realized in this package as util extension is very relevant there.

**Comment by RyanZim** [comment]
Yeah, not sure how the logic for that would work; in any case, out of scope for this package; should be it's own package if you want a util library for this.
