### ISSUE TITLE
Does not seem to work with Immutable.js

### ISSUE THREAD

**Issue by born2net** [ExodusMovement/redux-watch#2]
Hi,
I have Immutable.js map in the store that I am trying to listen to changes on:

as in:

```
let w = watch(appStore.getState, 'notify.currentAction', isEqual);
```

and yet I don't get an event for when Map currentAction gets modified (if I removed currentAction all works per reducer only)

is that not supported?

regards

Sean

**Comment by born2net** [comment]
found problem, so closing...

**Comment by shpleef** [comment]
@born2net how did u solve it? i am stuck at the same place

**Comment by born2net** [comment]
I ended up creating my own version of the lib (with some added helper methods)
see here:
https://github.com/born2net/angular2-redux-util

**Comment by Danetag** [comment]
For those who still want to use the library, there's a fix. When you create your watchers:

- Pass a function that returns the `.toJS()` version on your store
- Pass a compare function using `_.isEqual()` (or any other function to compare but this one is pretty good)

Example:
```
import store from 'store';
import watch from 'redux-watch';
import _ from 'underscore';

const compare = (a, b) => {
    return _.isEqual(a, b);
};

// create watchers
const pathExample = 'app.isLoaded'; 
const callback = (appLoaded, prevAppLoaded) => {
   console.log('app loaded!', appLoaded);
};

const watcher = watch(() => { return store.getState().toJS(); }, pathExample, compare);
const subscription = store.subscribe(watcher(callback));

```

**Comment by Danetag** [comment]
Actually, forget about my last comment. It works, but it's really, really slow and use immutable.js in a bad way.

Inspired by the work on the library, we created [redux-watch-immutable](https://www.npmjs.com/package/redux-watch-immutable) that just works for immutable object (and it's crazy fast!)
