### ISSUE TITLE
Problem when subscriber dispatch action

### ISSUE THREAD

**Issue by gitim** [ExodusMovement/redux-watch#3]
Hi! I have code, that has the same logic as the following:

``` js
'use strict';

var createStore = require('redux').createStore;
var watch = require('redux-watch');

function foo(state, action) {
    state = state || {a: null, b: {c: null, d: null}};
    switch (action.type) {
        case 'action1':
            return Object.assign({}, state, {
                a: 1,
                b: {
                    c: 2,
                    d: 3
                }
            });
        default:
            return state;
    }
}

function bar(state, action) {
    state = state || {};
    switch (action.type) {
        case 'action2':
            return Object.assign({}, state, action.data);
        default:
            return state;
    }
    return state;
}

function reducer(state, action) {
    state = state || {};
    return {
        foo: foo(state.foo, action),
        bar: bar(state.bar, action)
    };
}

var store = createStore(reducer);
store.subscribe(watch(store.getState, 'foo')(() => {
    // calculate some data
    var data = {e: [1,2,3], f: {}};
    store.dispatch({type: 'action2', data: data});
}));

store.dispatch({type: 'action1'});
```

And when I am using redux-watch I get `Maximum call stack size exceeded` error, but if i swap [14](https://github.com/jprichardson/redux-watch/blob/master/index.js#L14) and [15](https://github.com/jprichardson/redux-watch/blob/master/index.js#L15) lines in redux-watch it works fine. Am I using redux or redux-watch in wrong way, or it is a bug?

**Comment by jprichardson** [comment]
You're never handling `action2`, which would imply that you're modifying the state every time, but I'm not seeing that. What happens if you remove the `redux-watch` code?

**Comment by gitim** [comment]
Oh, sorry, I modified the example. 

> What happens if you remove the redux-watch code?

in my project, I use a fork of the redux-watch with swapped 14,15 lines, if I remove it, I will get `Maximum call stack size exceeded` again, because `action1 dispatched` and some subtree (`foo`) of the store changes, the subscriber do some work, than it dispatches `action2` and another subtree (`bar`) changes, and the subscriber called again, but it shouldn't, because it is interested only in changes of the first subtree (`foo`).

**Comment by gitim** [comment]
any updates?

**Comment by ciokan** [comment]
same issue. I have a route push when a certain state changes. it runs in a loop unfortunately.

**Comment by jprichardson** [comment]
Hmm. Ok. @gitim is your snippet above updated to reproduce this issue?

**Comment by gitim** [comment]
@jprichardson, yes

**Comment by fanatid** [comment]
@gitim if you will use `setTimeout`/`setImmediate` in watch function, all will works:

``` js
store.subscribe(watch(store.getState, 'foo')(() => {
    // calculate some data
    setImmediate(function () {
        var data = {e: [1,2,3], f: {}};
        store.dispatch({type: 'action2', data: data});
    })
}));
```

but you're right, lines order should be changed https://github.com/jprichardson/redux-watch/blob/011300f80b543d45c2ad256829dd186ce00abd08/index.js#L14-L15
moreover, maybe will better call `fn` through `setImmediate`:

``` js
function watch (getState, objectPath, compare) {
  compare = compare || defaultCompare
  var baseVal = getValue(getState(), objectPath)
  return function w (fn) {
    return function () {
      var newVal = getValue(getState(), objectPath)
      if (compare(baseVal, newVal)) return
      baseVal = newVal
      setImmediate(fn, newVal, baseVal, objectPath)
    }
  }
}
```

**edited**: not just swap, something like this:

``` js
var newVal = getValue(getState(), objectPath)
if (compare(baseVal, newVal)) return
var _oldVal = baseVal
baseVal = newVal
setImmediate(fn, newVal, _oldVal, objectPath)
```

**Comment by born2net** [comment]
tx for the fix, I did something similar as workaround and was going to submit but glad to see a fix was put in.
