### ISSUE TITLE
Trouble with storing "currentValue"

### ISSUE THREAD

**Issue by 3cL1p5e7** [ExodusMovement/redux-watch#9]
Hi!)
Thank you for this little beautiful library, i like it)
But i find problem:
If current state is:
```
var state = {
  messages: {
    state: none,
    list: [{
      text: 'first text' // will be changed
    }]
  }
}
```
I make
```
let w = watch(store.getState, 'messages')
store.subscribe(w((newVal, oldVal, objectPath) => {
  // code
}))
```
And i had change ``` state.messages.list[0].text = 'second text'; ```
Watcher does not fired.

Explaination:
you are store variable ```currentValue``` as object (state.messages), but if ```list```-element changed, ```currentValue``` changes(refreshed) automaticly and will be equal to ```newValue``` in next comparing. ```messages.list```  and each element inside array are links to memory slot inside ```messages``` object.

The simpliest solve of this is store ```currentValue``` as string for cloning list's elements:
```
'use strict'
var getValue = require('object-path').get

function defaultCompare (a, b) {
  return a === b
}

function watch (getState, objectPath, compare) {
  compare = compare || defaultCompare
  var currentValue = JSON.stringify(getValue(getState(), objectPath));
  // instead of // var currentValue = getValue(getState(), objectPath);
  return function w (fn) {
    return function () {
      var newValue = JSON.stringify(getValue(getState(), objectPath))
      // instead of // var newValue = getValue(getState(), objectPath)
      if (!compare(currentValue, newValue)) {
        var oldValue = currentValue
        currentValue = newValue
        fn(JSON.parse(newValue), JSON.parse(oldValue), objectPath)
      }
    }
  }
}

module.exports = watch
```
P.S. If subscribe to 'messages.list':
```
let w = watch(store.getState, 'messages.list')
store.subscribe(w((newVal, oldVal, objectPath) => {
  // code
}))
```
problem will not be solved

**Comment by fanatid** [comment]
@3cL1p5e7 if you use it in redux, state should be immutable, you can not change text as 
```js
state.messages.list[0].text = 'second text';
```
should be:
```js
state = { ...state, messages: [{ ...state.messages.list[0], text: 'second text' }, ...state.messages.list.slice(1)] }
```

if you still want change as property, you can pass custom comparator, in your case it will be `lodash.isEqual`

**Comment by 3cL1p5e7** [comment]
@fanatid Thank you very much!)))
